name: Set up project
inputs:
  python-version:
    description: Python version
  python-version-file:
    description: Python version

runs:
  using: composite

  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        python-version-file: ${{ inputs.python-version-file }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install the project
      run: uv sync --locked --all-extras --dev
      shell: bash
