name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  code-analysis:
    name: Code analysis using Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: False
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up project
        uses: ./.github/actions/setup-project
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint python files with black
        run: uv run black --diff --check $(git ls-files '*.py')

      - name: Lint python files with mypy
        run: uv run mypy $(git ls-files '*.py')

      - name: Lint python files with ruff
        run: uv run ruff check $(git ls-files '*.py')

      - name: Lint YAML files with yamllint
        run: uv run yamllint $(git ls-files '*.yml' '*.yaml')

  security:
    name: Security
    uses: ./.github/workflows/security.yml
