name: Schedule CI

permissions:
  contents: read
  pull-requests: write

on:
  schedule:
    - cron: 30 5 * * *

jobs:
  configure:
    name: Configure
    uses: ./.github/workflows/configure.yml

  security:
    name: Security
    uses: ./.github/workflows/security.yml
    needs: configure
    with:
      environments: ${{ needs.configure.outputs.environments }}
