name: Security

on:
  workflow_call:
  schedule:
    - cron: 30 5 * * *

jobs:
  security:
    name: Audit packages using Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    continue-on-error: True

    strategy:
      fail-fast: False
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up project
        uses: ./.github/actions/setup-project
        with:
          python-version: ${{ matrix.python-version }}

      - name: Audit python packages
        run: uv run pip-audit
